### ISSUE TITLE
Error running run.absCNseq

### ISSUE THREAD

**Issue by cassandratzh** [dakl/absCNseq#1]
Hi,

I encountered some problems while running run.absCNseq. 

I ran this code using the sample files - my.res.list <- run.absCNSeq("example.cn.txt", "example.snv.txt", "myResult", "Sample1", seq.type="WES", min.seg.len=200).

There's an error message stating 
Error in data.frame(x = mg, y = fb, wt = wts.het, lqs = qs[snp2seg], ix = 0) : 
  arguments imply differing number of rows: 0, 1 In addition: Warning message:
In fread(snv.fn) :
  Bumped column 1 to type character on data row 52, field contains 'GL000225.1'. Coercing previously read values in this column from logical, integer or numeric back to character which may not be lossless; e.g., if '00' and '000' occurred before they will now be just '0', and there may be inconsistencies with treatment of ',,' and ',NA,' too (if they occurred in this column before the bump). If this matters please rerun and set 'colClasses' to 'character' for this column. Please note that column type detection uses the first 5 rows, the middle 5 rows and the last 5 rows, so hopefully this message should be very rare. If reporting to datatable-help, please rerun and include the output from verbose=TRUE.

Do anyone have any idea how to solve this? Thanks.

**Comment by dakl** [comment]
This is not the main code base for absCNseq and I'm not an author of the code. You should contact the authors of the paper for help with the package.

http://bioinformatics.oxfordjournals.org/content/30/8/1056.long
